// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package crypto

import (
	"crypto/config"
	"crypto/internal/delivery/http"
	"crypto/pkg/repository/mysql/database"
	"crypto/pkg/service/controller/restctl"
	"crypto/pkg/service/core/rest"
	"crypto/pkg/wireset"
)

// Injectors from wire.go:

func Initialize() (Application, error) {
	configSetup, err := config.New()
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configSetup)
	if err != nil {
		return Application{}, err
	}
	dbClient, err := database.NewDBClient()
	if err != nil {
		return Application{}, err
	}
	dbRepository := database.NewDBRepository(dbClient)
	useCase := rest.NewUseCase(dbRepository)
	restCtl := restctl.NewRestCtl(useCase)
	httpServer := http.NewHttpServer(restCtl)
	application := newApplication(logger, configSetup, httpServer)
	return application, nil
}
