// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package migrate

import (
	"crypto/config"
	"crypto/pkg/repository/mysql/database"
	"crypto/pkg/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configSetup, err := config.New()
	if err != nil {
		return Application{}, err
	}
	dbClient, err := database.NewDBClient()
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configSetup)
	if err != nil {
		return Application{}, err
	}
	application := newApplication(configSetup, dbClient, logger)
	return application, nil
}
